backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Trees'
    folder: 'src/pages/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'select',
          default: 'blog-post',
          options: ['blog-post', 'alt-layout'],
        }
      - {
          label: 'Title Type',
          name: 'title_type',
          widget: 'select',
          default: 'National Champion:',
          options:
            ['National Champion:', 'Former Champion:', 'National Co Champion:'],
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Common Name', name: 'common_name', widget: 'string' }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Year Crowned', name: 'crowned', widget: 'string' }
      - { label: 'Year Photographed', name: 'photographed', widget: 'string' }
      - { label: 'Circumference', name: 'circumference', widget: 'string' }
      - { label: 'Height', name: 'height', widget: 'string' }
      - { label: 'Avg Crown Spread', name: 'crown_spread', widget: 'string' }
      - { label: 'Total AF Points', name: 'total_af_points', widget: 'string' }
      - {
          label: Image 1,
          name: image1,
          widget: object,
          fields:
            [
              { label: Image, name: image, widget: image },
              { label: Alt, name: alt, widget: string },
            ],
        }
      - {
          label: Image 2,
          name: image2,
          widget: object,
          fields:
            [
              { label: Image, name: image, widget: image },
              { label: Alt, name: alt, widget: string },
            ],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'news'
    label: 'News'
    folder: 'src/pages/news'
    create: false
    fields:
      - {
          label: 'Template Key',
          name: 'templateKey',
          widget: 'hidden',
          default: 'info-page',
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
